version: '3.9'

services:
  project:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./project:/project
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./env_files/env/.env.project
      - ./env_files/env/.env.db
    depends_on:
      - psql
  psql:
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./env_files/env/.env.db