# Generated by Django 4.2.7 on 2023-12-29 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Último Nome')),
                ('email', models.EmailField(max_length=320, unique=True, verbose_name='Email')),
                ('password', models.CharField(editable=False, max_length=240, verbose_name='Senha')),
                ('phone', models.CharField(default=None, max_length=15, null=True, verbose_name='Celular')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Tentativas de login com a senha incorreta. Caso ultrapasse o limite definido nas configurações o usuário precisará redefini-la', verbose_name='Tentativas')),
                ('is_staff', models.BooleanField(default=False, help_text='Define se o usuário pode acessar o site Administrativo.', verbose_name='Administrador')),
                ('is_superuser', models.BooleanField(default=False, editable=False, help_text='Define se o usuário possui todas as permissões. ', verbose_name='Superusuário')),
                ('is_active', models.BooleanField(default=True, help_text='Define se o usuáruio deveria ser tratado como ativo. Desmarque ao invés de excluir contas.', verbose_name='Ativo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entrou em')),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Último Login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario_users',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('bill', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Conta')),
                ('limit', models.DecimalField(decimal_places=2, default=0, help_text='Define o valor máximo da conta à prazo. Válido apenas para Usuários Premium.', max_digits=6, verbose_name='Limite')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=2, verbose_name='Gênero')),
                ('born_at', models.DateField(verbose_name='Nascimento')),
                ('favorites', models.ManyToManyField(blank=True, related_name='unit_favorite', to='produto.unit', verbose_name='Favoritos')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customer', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'usuario_customers',
                'permissions': [('payments', 'Can view self payments'), ('favorites', 'Can view favorites'), ('add_favorite', 'Can add favorite'), ('remove_favorite', 'Can remove favorite'), ('buy_in_term', 'Can buy in term')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantia')),
                ('method', models.CharField(choices=[('M', 'Dinheiro'), ('P', 'Pix'), ('C', 'Cartão')], default='P', max_length=1, verbose_name='Método')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.customer', verbose_name='Ciente')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'usuario_payments',
                'ordering': ['-date_time'],
            },
        ),
    ]
