# Generated by Django 4.2.4 on 2023-08-26 00:20

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(blank=True, default=None, max_length=120, null=True, verbose_name='Último Nome')),
                ('email', models.EmailField(max_length=320, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=240, verbose_name='Senha')),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Tentativas de login com a senha incorreta. Caso ultrapasse o limite definido nas configurações o usuário precisará redefini-la', verbose_name='Tentativas')),
                ('is_staff', models.BooleanField(default=False, help_text='Define se o usuário pode acessar o site Administrativo.', verbose_name='Administrador')),
                ('is_superuser', models.BooleanField(default=False, editable=False, help_text='Define se o usuário possui todas as permissões. ', verbose_name='Superusuário')),
                ('is_active', models.BooleanField(default=True, help_text='Define se o usuáruio deveria ser tratado como ativo. Desmarque ao invés de excluir contas.', verbose_name='Ativo')),
                ('date_joined', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Entrou em')),
                ('last_login', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Último Login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario_users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
