# Generated by Django 4.2.4 on 2023-09-04 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='default',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
