# Generated by Django 4.2.4 on 2023-11-15 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_user_date_joined_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='user_customer', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
