# Generated by Django 4.2.4 on 2023-11-16 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora'),
        ),
    ]
