# Generated by Django 4.2.4 on 2023-11-17 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_customer_options_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_customer', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
