# Generated by Django 4.2.7 on 2023-12-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_customer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('payments', 'Can view self payments'), ('favorites', 'Can view self payments'), ('add_favorite', 'Can add favorite'), ('remove_favorite', 'Can remove favorite'), ('buy_in_term', 'Can buy in term')], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
