# Generated by Django 4.2.7 on 2023-12-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_customer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=2, verbose_name='Gênero'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('M', 'Dinheiro'), ('P', 'Pix'), ('C', 'Cartão')], default='P', max_length=1, verbose_name='Método'),
        ),
    ]
