# Generated by Django 4.2.7 on 2023-12-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_customer_gender_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Define o valor máximo da conta à prazo. Válido apenas para Usuários Premium.', max_digits=5, verbose_name='Limite'),
        ),
    ]
