# Generated by Django 4.2.7 on 2023-12-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_customer_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_time'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='customer',
            name='born',
            field=models.DateField(default='2000-10-10', verbose_name='Nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='bill',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Define o valor máximo da conta à prazo. Válido apenas para Usuários Premium.', max_digits=6, verbose_name='Limite'),
        ),
    ]
