# Generated by Django 4.2.7 on 2023-12-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_alter_payment_options_customer_born_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True, verbose_name='Celular'),
        ),
    ]
