# Generated by Django 4.2.7 on 2023-12-29 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, help_text='Deixe vazio para gerar automaticamente.', max_length=120, unique=True, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'produto_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(max_length=400, verbose_name='Descrição')),
                ('slug', models.SlugField(blank=True, help_text='Deixe vazio para gerar automaticamente.', max_length=120, unique=True, verbose_name='Link')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto_products',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Variedade',
                'verbose_name_plural': 'Variedades',
                'db_table': 'produto_varieties',
            },
        ),
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.variety', verbose_name='Variedade')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
                'db_table': 'produto_variations',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('sku', models.CharField(max_length=12, unique=True, verbose_name='Código')),
                ('image_lg', models.ImageField(upload_to='produtos/lg/', verbose_name='Imagem')),
                ('image_sm', models.ImageField(editable=False, upload_to='produtos/sm/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço')),
                ('promotional', models.DecimalField(blank=True, decimal_places=2, help_text='Preço acima do original que mostrará riscado.', max_digits=6, null=True, verbose_name='Preço promocional')),
                ('stock', models.PositiveIntegerField(verbose_name='Estoque')),
                ('booked', models.PositiveIntegerField(default=0, verbose_name='Reservado')),
                ('showcase', models.BooleanField(default=True, verbose_name='Mostrar na vitrine')),
                ('released', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Lançado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.product', verbose_name='Produto')),
                ('variations', models.ManyToManyField(blank=True, related_name='variations_units', to='produto.variation', verbose_name='Variações')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'produto_units',
                'permissions': [('cart', 'Can view cart'), ('add_to_cart', 'Can add to cart'), ('increment_cart', 'Can increment cart'), ('decrement_cart', 'Can decrement cart'), ('clean_cart', 'Can clear cart'), ('remove_from_cart', 'Can remove from cart')],
            },
        ),
    ]
