# Generated by Django 4.2.4 on 2023-09-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='showcase',
            field=models.BooleanField(default=True, verbose_name='Mostrar na vitrine'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='promotional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço acima do original que mostrará riscado.', max_digits=5, null=True, verbose_name='Preço promocional'),
        ),
    ]
