# Generated by Django 4.2.4 on 2023-11-15 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_unit_showcase_alter_unit_promotional'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='released',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Lançado em'),
        ),
    ]
