# Generated by Django 4.2.4 on 2023-11-17 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_unit_released'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'permissions': [('add_to_cart', 'Can add to cart'), ('add_one_to_cart', 'Can add one to cart'), ('cart', 'Can view cart'), ('clear_cart', 'Can clear cart'), ('remove_from_cart', 'Can remove from cart')], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
    ]
