# Generated by Django 4.2.4 on 2023-11-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_remove_category_subcategory_of_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Deixe vazio para gerar automaticamente.', max_length=120, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Deixe vazio para gerar automaticamente.', max_length=120, unique=True, verbose_name='Link'),
        ),
    ]
