# Generated by Django 4.2.7 on 2023-11-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_remove_unit_image_unit_image_lg_unit_image_sm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image_lg',
            field=models.ImageField(upload_to='produtos/lg/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image_sm',
            field=models.ImageField(editable=False, upload_to='produtos/sm/'),
        ),
    ]
