# Generated by Django 4.2.7 on 2023-12-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_unit_image_lg_alter_unit_image_sm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'permissions': [('cart', 'Can view cart'), ('add_to_cart', 'Can add to cart'), ('add_from_list_to_cart', 'Can add from list to cart'), ('increment_cart', 'Can increment cart'), ('decrement_cart', 'Can decrement cart'), ('clean_cart', 'Can clear cart'), ('remove_from_cart', 'Can remove from cart')], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
    ]
