# Generated by Django 4.2.7 on 2023-12-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_unit_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name': 'Variedade', 'verbose_name_plural': 'Variedades'},
        ),
        migrations.AlterField(
            model_name='variation',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.variety', verbose_name='Variedade'),
        ),
    ]
