# Generated by Django 4.2.7 on 2023-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0011_alter_unit_promotional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Descrição'),
        ),
    ]
