# Generated by Django 4.2.4 on 2023-09-02 20:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('F', 'Finalizado'), ('B', 'Reservado'), ('E', 'Expirado'), ('C', 'Consumido')], default='F', max_length=1, verbose_name='Status')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço Total')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='Quantidade Total')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='pedido.order', verbose_name='Pedido')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.RESTRICT, to='produto.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'pedido_order_units',
            },
        ),
    ]
