# Generated by Django 4.2.7 on 2023-12-29 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('F', 'Finalizado'), ('B', 'Reservado'), ('E', 'Expirado'), ('R', 'Reprovado'), ('C', 'Consumido'), ('A', 'Cancelado')], default='F', max_length=1, verbose_name='Status')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('booked_upto', models.DateTimeField(blank=True, default=None, help_text='Preencha apenas se estiver reservado', null=True, verbose_name='Reservado até')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Preço Total')),
                ('total_quantity', models.PositiveIntegerField(blank=True, default=0, verbose_name='Quantidade Total')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Desconto')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='usuario.customer', verbose_name='Cliente')),
                ('payment', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuario.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido_orders',
                'ordering': ['-date_time'],
                'permissions': [('self_orders', 'Can view self orders'), ('cancel_book', 'Can cancel booking')],
            },
        ),
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_units', to='pedido.order', verbose_name='Pedido')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produto.unit', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'pedido_order_units',
            },
        ),
    ]
