# Generated by Django 4.2.4 on 2023-11-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_orderunit_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('self_orders', 'Can view self orders')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
    ]
