# Generated by Django 4.2.7 on 2023-12-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_alter_customer_limit'),
        ('pedido', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.RESTRICT, to='usuario.payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('F', 'Finalizado'), ('R', 'Reprovado'), ('B', 'Reservado'), ('E', 'Expirado'), ('C', 'Consumido'), ('A', 'Carrinho abandonado')], default='F', max_length=1, verbose_name='Status'),
        ),
    ]
