# Generated by Django 4.2.7 on 2023-12-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_order_payment_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('F', 'Finalizado'), ('B', 'Reservado'), ('E', 'Expirado'), ('R', 'Reprovado'), ('C', 'Consumido'), ('A', 'Carrinho abandonado')], default='F', max_length=1, verbose_name='Status'),
        ),
    ]
