# Generated by Django 4.2.7 on 2023-12-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booked_upto',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Reservado até'),
        ),
    ]
