# Generated by Django 4.2.7 on 2023-12-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_order_booked_upto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_time'], 'permissions': [('self_orders', 'Can view self orders')], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='booked_upto',
            field=models.DateTimeField(blank=True, default=None, help_text='Preencha apenas se estiver reservado', null=True, verbose_name='Reservado até'),
        ),
    ]
